server:
  port: 8084

spring:
  application:
    name: interaction-service
  config:
    import: optional:file:.env[.properties],optional:file:../../.env[.properties],optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

