server:
  port: 8083

spring:
  application:
    name: comment-service
  config:
    import: optional:file:.env[.properties],optional:file:../../.env[.properties],optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
